#ifndef MAPLE_COMMAND_CODES_H_
#define MAPLE_COMMAND_CODES_H_

#define MAPLE_COMMAND_REQUEST_DEVINFO  1
#define MAPLE_COMMAND_REQUEST_DEVINFOX 2
#define MAPLE_COMMAND_RESET_DEVICE     3
#define MAPLE_COMMAND_SHUTDOWN_DEVICE  4
#define MAPLE_RESPONSE_DEVINFO         5
#define MAPLE_RESPONSE_DEVINFOX        6
#define MAPLE_RESPONSE_ACK             7
#define MAPLE_RESPONSE_DATA            8
#define MAPLE_COMMAND_GET_CONDITION    9
#define MAPLE_COMMAND_GET_MEMINFO      10
#define MAPLE_COMMAND_BLOCK_READ       11
#define MAPLE_COMMAND_BLOCK_WRITE      12
#define MAPLE_COMMAND_SET_CONDITION    14

#endif /* MAPLE_COMMAND_CODES_H_ */
